// const ACCESS_TOKEN = process.env.ACCESS_TOKEN;
import { TfiControlShuffle } from "react-icons/tfi";
import { IMDB_URL, options, ACCESS_TOKEN } from "./index";

export default async function getAllMovie(
  genre: string
): Promise<AllMovieProps> {
  const movieGenre =
    genre === "fetchTopRated" ? "movie/top_rated" : "trending/all/week";
  const req = await fetch(IMDB_URL + "/" + movieGenre, options);
  if (!req.ok) {
    throw Error("failed to fetch  treading imdb movie ");
  }
  const response = (await req.json()) as unknown;
  return response as AllMovieProps;
}
// Generated by https://quicktype.io

export interface AllMovieProps {
  page: number;
  results: Result[];
  total_pages: number;
  total_results: number;
}

export interface Result {
  adult: boolean;
  backdrop_path: string;
  id: number;
  title: string;
  original_language: OriginalLanguage;
  original_title: string;
  overview: string;
  poster_path: string;
  media_type: MediaType;
  genre_ids: number[];
  popularity: number;
  release_date: string;
  video: boolean;
  vote_average: number;
  vote_count: number;
}

export enum MediaType {
  Movie = "movie",
}

export enum OriginalLanguage {
  En = "en",
  Es = "es",
}
